# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.12.0
  aws-cli: circleci/aws-cli@2.0
  aws-eks: circleci/aws-eks@0.2.3

jobs:
  lint:
    docker:
    # Use the same Docker base as the project
    - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
  

      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint 
  
  build-image:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - setup_remote_docker:
            version: 19.03.13
      - run:
          name: Build Image
          command: |
            docker build --tag udacitycapstone .
      - run:
          name: Push Image
          command: |
            docker login --username adileyzekmoon --password ${dockerpw} &&\
            docker image tag udacitycapstone adileyzekmoon/udacitycapstone
            docker image push adileyzekmoon/udacitycapstone

  deploy-kube:
    executor: aws-eks/python3
    steps:
        - checkout
        - aws-eks/update-kubeconfig-with-authenticator:
            cluster-name: udacity-eks
            install-kubectl: true
            aws-region: us-east-1
            verbose: true
        # - kubernetes/create-or-update-resource:
        #     resource-file-path: "kubernetes.yml"
        #     get-rollout-status: true
        #     resource-name: adileyzekmoon/udacitycapstone
        # - kubernetes/create-or-update-resource:
        #     resource-file-path: "kubernetes.yml"
        - run:
            name: Check on pod status
            command: |
              aws configure list
              kubectl config use-context arn:aws:eks:us-east-1:823809779962:cluster/udacity-eks
              kubectl apply -f kubernetes.yml
        - run:
            name: Check on pod status
            command: |
              kubectl get pods

workflows:
  default:
    jobs:
      # - lint
      # - build-image
          # requires: [lint]
      - deploy-kube
          # requires: [build-image]
  