# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.12.0

jobs:
  lint:
    docker:
    # Use the same Docker base as the project
    - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
  

      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint 
  
  build-image:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - setup_remote_docker:
            version: 19.03.13
      - run:
          name: Build Image
          command: |
            docker build --tag udacitycapstone .
      - run:
          name: Push Image
          command: |
            docker login --username adileyzekmoon --password baozakeruga &&\
            docker image tag udacitycapstone adileyzekmoon/udacitycapstone
            docker image push adileyzekmoon/udacitycapstone

  deploy-kube:
    docker:
      - image: amazon/aws-cli
    steps:
        - checkout
        - run:
            name: configure AWS CLI
            command: |
              aws configure import --csv file://credentials.csv
              aws configure list
              aws configure list-profiles
              export AWS_PROFILE=prometheus_udacity
        - run:
            name: Update Kubeconfig
            command: |
              aws eks --region us-east-1 update-kubeconfig --name udacity-eks --profile prometheus_udacity
        - kubernetes/install-kubectl
        - run:
            name: Deploy to Kubernetes
            command: |
              kubectl config use-context arn:aws:eks:us-east-1:823809779962:cluster/udacity-eks
              kubectl apply -f kubernetes.yaml
        - run:
            name: Check on pod status
            command: |
              kubectl get pods

workflows:
  default:
    jobs:
      # - lint
      # - build-image
          # requires: [lint]
      - deploy-kube
          # requires: [build-image]
  